baseURL = "https://acyanbird.tech/"
languageCode = "zh-cn"
title = "Nighthawk's nest"
theme = "github-style"
# theme = "github-style-plus"
pygmentsCodeFences = true
pygmentsUseClasses = false
buildDrafts = false
PygmentsStyle = "tango"
enableEmoji = true


[params]
  author = "山奈"
  description = "For the people who are still online."
  github = "acyanbird"
  email = "acyanbird@gmail.com"
  url = "https://acyanbird.tech"
#   keywords = "blog, google analytics"
  # rss = true
  # userStatusEmoji = "😀"
  favicon = "/images/ava_c_trans.png" #标签页的那个小图标，先不管
  avatar = "/images/ava_c.png"
  headerIcon = "/images/ava_c.png"
  location = "Shenzhen, China"
  enableGitalk = true
  enableSearch = true

[outputs]
  home = ["html", "json"]

[outputFormats.json]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = false

  [params.gitalk]
    clientID = "Ov23lioPbYI2h4agywvu"
    clientSecret = "ce9bb78db00344b91c6f8c6ed1064a8e2529716b"
    repo = "blog-comment"
    owner = "acyanbird"
    admin = "acyanbird"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false


  [[params.links]]
    title = "bilibili"
    href = "https://space.bilibili.com/205319947"
    icon = "images/bilibili.svg"

  [[params.links]]
    title = "QQ Group"
    icon = "images/qq.svg"
    href = "https://qm.qq.com/q/cXb0hh1uC"

lastmod = true
[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

# [services]
#   [services.googleAnalytics]
#     ID = "UA-123456-789"


